### ISSUE TITLE
Paypal Payflow Pro Loader Issue On Checkout

### ISSUE THREAD

**Issue by vishalpatel14** [ManaLight/magento2-bundlejs#2]
Hello Team

We have notice the error with Paypal Payflow Pro while we do checkout while entering the card details on website and click Place Order button load the loader and website get stuck on loader.

PFA for your reference.

![Checkout](https://github.com/ManaLight/magento2-bundlejs/assets/16519746/727db0d2-ecef-45c2-94fc-d8434c0b9c77)

**Comment by ManaLight** [comment]
@vishalpatel14 Thank you for reporting the issue! In case you haven't, please disable/remove the extension until the issue gets fixed.

Do you have a dev site so that we can debug it directly?
For more convenience, could you please add our dev's skype as well ?
Thanks.

**Comment by ManaLight** [comment]
@vishalpatel14 It will take time to set up Paypal Payflow Pro. 

As per your suggestion, I created another config to disable the extension on the checkout pages on the tag version 1.3.2-alpha1:

![image](https://github.com/ManaLight/magento2-bundlejs/assets/24420996/6bcaa2d8-1d24-4e35-98d5-335d0fb97aec)

```
composer require pure_mashiro/magento2-bundlejs:^1.3.2-alpha1
```

**Comment by ManaLight** [comment]
@vishalpatel14 I can replicate the issue with the Cybersource payment method. The issue happens because the POST request returns a result layout ```\Magento\Framework\View\Result\Layout```. This layout is cacheable because it doesn't have ```cacheable="false"``` in the XML file, but the POST request itself always bypasses the full-page cache.

```$subject->getLayout()->isCacheable()``` should be changed to ```!$this->request->isAjax() && ($this->request->isGet() || $this->request->isHead()) && $layout->isCacheable()```

To avoid more unexpected issues, I also add a new config to limit the delay js on some types of static pages only: https://github.com/ManaLight/magento2-bundlejs/commit/cd3f444664ae5bc7bb9618112b515e72d3348783
Please update the extension to the latest version and help me check it again. Thanks.

**Comment by replysharma** [comment]
Thank you so much @ManaLight for your superfast response as always but I face another issue after upgrading the plugin.
I restart the collect JS bundle again but this time I do not get success message.

Do I need to follow any other step, If you can help here then it will good because this time I am struggling with auto/manual collecting the bundle js.

I am keep getting the auto collecting is in process, please wait. I waited around 30-40 minutes but no luck this time, also suggest me how do I make sure that everything is getting setup successfully.

**Comment by ManaLight** [comment]
@vishalpatel14 The issue seems to be resolved in the new version so I will close the issue in 1 week. Thanks!
